### ISSUE TITLE
[BUG] Missing js, css files included from appropriate datapub-*** repo

### ISSUE THREAD

**Issue by mbeilin** [datopian/ckanext-datapub#3]
While testing in NHS getting the following runtime error:
```
Error - <type 'exceptions.AttributeError'>: 'module' object has no attribute 'datapub/css/main.b4d771cb.chunk.css
``` 
as one of the files, we are pointing in [upload_module.html](https://github.com/datopian/ckanext-datapub/blob/master/ckanext/datapub/templates/datapub/snippets/upload_module.html
)
```
{% resource 'datapub/css/main.b4d771cb.chunk.css' %}

{% resource 'datapub/js/runtime-main.c155da57.js' %}
{% resource 'datapub/js/2.2599189b.chunk.js' %}
{% resource 'datapub/js/main.c4752953.chunk.js' %}

<div id="ResourceEditor"
     data-dataset-id="{{ pkg_name }}"
     data-api="{{ base_url }}"
     data-lfs="{{ h.extstorage_lfs_url() }}"
     data-auth-token="{{ api_key }}"
     data-organization-id="{{ h.extstorage_organization_name(pkg_name) }}"
     data-resource-id="{{ resource_id }}">
</div>
```
We need to have these files included in this repo here:
https://github.com/datopian/ckanext-datapub/tree/master/ckanext/datapub/fanstatic
currently excluded with [`gitignore`](https://github.com/datopian/ckanext-datapub/blob/master/ckanext/datapub/fanstatic/.gitignore)

**Comment by anuveyatsu** [comment]
@mbeilin these 4 files (1 css and 3 js) are built bundles from the React app. We can simply comment them out but the idea is that developers update the filenames once they have build their own bundles.

We don't want to commit built bundles in the git repo because it is unreadable and often large in size.

Also, please check the small note in the README which states:

> Next, you need to update the template to include correct bundles. In /templates/datapub/snippets/upload_module.html, edit the file names of the modules.
