### ISSUE TITLE
Enable cloning react app from a private git repo

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ckanext-datapub#6]
At the moment the datapub app we clone from using `DATAPUB_APP` env variable must be public. Is there a way to be able to set this up so we can access private git repos (using a token or username and password of a read-only user?)

https://github.com/datopian/ckanext-datapub/blob/master/sync.sh#L1

```
DATAPUB_APP=${1:='https://github.com/datopian/datapub'}
```

**Comment by zelima** [comment]
Nothing needs to be modified on this level, `sync.sh` assepts URL for the repository to clone from. Meaning we can pass URL with username and token inside Eg:

https://username:password@github.com/datopian/datapub-gdx

I've tested and it's working perfectly fine

**Comment by zelima** [comment]
FIXED
